import socket
import json
import time

# Example usage
port = 12002  # Replace with the port your server is listening on
commands = []
commandCreate = {"Command": 0, "Args": ["test","10","15"]} 
commandProbe = {"Command": 1, "Args": ["123"]}
commandStop = {"Command": 4}
commandInfo = {"Command": 5}

def send_json_command(port, commands):
    # Create a socket (SOCK_STREAM means a TCP socket)
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as sock:
        # Connect to server and send data
        sock.connect(("127.0.0.1", port))
        sock.sendall(json.dumps({"Command": 0, "Args": ["test","10","15"]}).encode('ASCII'))
        while True:
            time.sleep(0.1) 
            sock.sendall(json.dumps({"Command": 5}).encode('ASCII'))
            received = sock.recv(1024).decode('utf-8')
            if json.loads(received)["Status"] == "OK":
                break
            
        for command in commands:
            time.sleep(0.1) 
            sock.sendall(json.dumps(command).encode('ASCII'))
            if command["Command"] == 5:
                # Receive data from the server and shut down
                received = sock.recv(1024).decode('utf-8')
                print(received)
    # return received

commands.append(commandProbe)
commands.append(commandInfo)
commands.append(commandProbe)
commands.append(commandInfo)
commands.append(commandProbe)
commands.append(commandInfo)
commands.append(commandInfo)
commands.append(commandProbe)
commands.append(commandInfo)
commands.append(commandProbe)
commands.append(commandInfo)
commands.append(commandProbe)
commands.append(commandInfo)
commands.append(commandProbe)
commands.append(commandInfo)
commands.append(commandProbe)
commands.append(commandInfo)
commands.append(commandInfo)
commands.append(commandProbe)
commands.append(commandInfo)
commands.append(commandProbe)
commands.append(commandInfo)
commands.append(commandProbe)
commands.append(commandInfo)
commands.append(commandProbe)
commands.append(commandInfo)
commands.append(commandProbe)
commands.append(commandInfo)
commands.append(commandInfo)
commands.append(commandProbe)
commands.append(commandInfo)
commands.append(commandProbe)
commands.append(commandInfo)
commands.append(commandProbe)
commands.append(commandInfo)
commands.append(commandProbe)
commands.append(commandInfo)
commands.append(commandProbe)
commands.append(commandInfo)
commands.append(commandInfo)
commands.append(commandProbe)
commands.append(commandInfo)
commands.append(commandProbe)
commands.append(commandInfo)
commands.append(commandProbe)
commands.append(commandInfo)
commands.append(commandProbe)
commands.append(commandInfo)
commands.append(commandProbe)
commands.append(commandInfo)
commands.append(commandInfo)
commands.append(commandProbe)
commands.append(commandInfo)
commands.append(commandProbe)
commands.append(commandInfo)
commands.append(commandProbe)
commands.append(commandInfo)
commands.append(commandProbe)
commands.append(commandInfo)
commands.append(commandProbe)
commands.append(commandInfo)
commands.append(commandInfo)
commands.append(commandProbe)
commands.append(commandInfo)
commands.append(commandProbe)
commands.append(commandInfo)
commands.append(commandProbe)
commands.append(commandInfo)
commands.append(commandProbe)
commands.append(commandInfo)
commands.append(commandProbe)
commands.append(commandInfo)
commands.append(commandInfo)
commands.append(commandProbe)
commands.append(commandInfo)
commands.append(commandProbe)
commands.append(commandInfo)
commands.append(commandProbe)
commands.append(commandInfo)
commands.append(commandProbe)
commands.append(commandInfo)
commands.append(commandProbe)
commands.append(commandInfo)
commands.append(commandInfo)
commands.append(commandProbe)
commands.append(commandInfo)
commands.append(commandProbe)
commands.append(commandInfo)
commands.append(commandProbe)
commands.append(commandInfo)
commands.append(commandProbe)
commands.append(commandInfo)
commands.append(commandProbe)
commands.append(commandInfo)
commands.append(commandInfo)
commands.append(commandProbe)
commands.append(commandInfo)
commands.append(commandProbe)
commands.append(commandInfo)
commands.append(commandProbe)
commands.append(commandInfo)
commands.append(commandProbe)
commands.append(commandInfo)
commands.append(commandProbe)
commands.append(commandInfo)
commands.append(commandInfo)
commands.append(commandProbe)
commands.append(commandInfo)
commands.append(commandProbe)
commands.append(commandInfo)
commands.append(commandProbe)
commands.append(commandInfo)
commands.append(commandProbe)
commands.append(commandInfo)
commands.append(commandProbe)
commands.append(commandInfo)
commands.append(commandInfo)
commands.append(commandProbe)
commands.append(commandInfo)
commands.append(commandProbe)
commands.append(commandInfo)
commands.append(commandProbe)
commands.append(commandInfo)
commands.append(commandProbe)
commands.append(commandInfo)
commands.append(commandProbe)
commands.append(commandInfo)
commands.append(commandInfo)
commands.append(commandProbe)
commands.append(commandInfo)
commands.append(commandProbe)
commands.append(commandInfo)
commands.append(commandProbe)
commands.append(commandInfo)
commands.append(commandProbe)
commands.append(commandInfo)
commands.append(commandProbe)
commands.append(commandInfo)
commands.append(commandInfo)
commands.append(commandProbe)
commands.append(commandInfo)
commands.append(commandProbe)
commands.append(commandInfo)
commands.append(commandProbe)
commands.append(commandInfo)
commands.append(commandProbe)
commands.append(commandInfo)
commands.append(commandProbe)
commands.append(commandInfo)
commands.append(commandInfo)
commands.append(commandProbe)
commands.append(commandInfo)
commands.append(commandProbe)
commands.append(commandInfo)
commands.append(commandProbe)
commands.append(commandInfo)
commands.append(commandProbe)
commands.append(commandInfo)
commands.append(commandProbe)
commands.append(commandInfo)
commands.append(commandInfo)
commands.append(commandProbe)
commands.append(commandInfo)
commands.append(commandProbe)
commands.append(commandInfo)

commands.append(commandStop)

response = send_json_command(port, commands)
